import { Level } from './types';

export const LEVELS: Level[] = [
  {
    id: 1,
    name: 'Başlangıç',
    description: 'Basit bir hedef. Fırlat ve vur!',
    projectiles: [{ type: 'normal', count: 3 }],
    targets: [
      {
        x: 600,
        y: 450,
        width: 40,
        height: 40,
        type: 'rectangle',
        material: 'wood',
        points: 100,
      },
    ],
    obstacles: [],
    requiredScore: 100,
    stars: { one: 100, two: 100, three: 100 },
  },
  {
    id: 2,
    name: 'İstif',
    description: 'Üst üste yığılmış kutuları devir!',
    projectiles: [{ type: 'normal', count: 3 }],
    targets: [
      {
        x: 600,
        y: 480,
        width: 40,
        height: 40,
        type: 'rectangle',
        material: 'wood',
        points: 50,
      },
      {
        x: 600,
        y: 430,
        width: 40,
        height: 40,
        type: 'rectangle',
        material: 'wood',
        points: 75,
      },
      {
        x: 600,
        y: 380,
        width: 40,
        height: 40,
        type: 'rectangle',
        material: 'wood',
        points: 100,
      },
    ],
    obstacles: [],
    requiredScore: 150,
    stars: { one: 150, two: 200, three: 225 },
  },
  {
    id: 3,
    name: 'Cam Kule',
    description: 'Kırılgan cam yapıyı yık!',
    projectiles: [{ type: 'normal', count: 4 }],
    targets: [
      {
        x: 550,
        y: 480,
        width: 30,
        height: 60,
        type: 'rectangle',
        material: 'glass',
        points: 50,
      },
      {
        x: 620,
        y: 480,
        width: 30,
        height: 60,
        type: 'rectangle',
        material: 'glass',
        points: 50,
      },
      {
        x: 585,
        y: 420,
        width: 70,
        height: 20,
        type: 'rectangle',
        material: 'glass',
        points: 100,
      },
    ],
    obstacles: [],
    requiredScore: 150,
    stars: { one: 150, two: 180, three: 200 },
  },
  {
    id: 4,
    name: 'Korumalı Hedef',
    description: 'Taş duvarın arkasındaki hedefi vur!',
    projectiles: [{ type: 'heavy', count: 2 }, { type: 'normal', count: 2 }],
    targets: [
      {
        x: 650,
        y: 450,
        radius: 20,
        type: 'circle',
        material: 'wood',
        points: 150,
      },
    ],
    obstacles: [
      {
        x: 550,
        y: 400,
        width: 20,
        height: 120,
        type: 'rectangle',
        material: 'stone',
        isStatic: false,
      },
    ],
    requiredScore: 150,
    stars: { one: 150, two: 200, three: 250 },
  },
  {
    id: 5,
    name: 'Platform Bulmacası',
    description: 'Eğik platformları kullan!',
    projectiles: [{ type: 'bouncy', count: 3 }],
    targets: [
      {
        x: 700,
        y: 350,
        width: 35,
        height: 35,
        type: 'rectangle',
        material: 'wood',
        points: 100,
      },
      {
        x: 650,
        y: 480,
        width: 35,
        height: 35,
        type: 'rectangle',
        material: 'wood',
        points: 100,
      },
    ],
    obstacles: [
      {
        x: 450,
        y: 450,
        width: 120,
        height: 10,
        type: 'rectangle',
        material: 'stone',
        isStatic: true,
        angle: -0.3,
      },
      {
        x: 600,
        y: 380,
        width: 100,
        height: 10,
        type: 'rectangle',
        material: 'stone',
        isStatic: true,
        angle: 0.3,
      },
    ],
    requiredScore: 150,
    stars: { one: 150, two: 180, three: 200 },
  },
  {
    id: 6,
    name: 'Karışık Malzemeler',
    description: 'Farklı malzemeleri tanı ve stratejini belirle!',
    projectiles: [{ type: 'normal', count: 3 }, { type: 'heavy', count: 1 }],
    targets: [
      {
        x: 550,
        y: 470,
        width: 40,
        height: 40,
        type: 'rectangle',
        material: 'glass',
        points: 50,
      },
      {
        x: 620,
        y: 470,
        width: 40,
        height: 40,
        type: 'rectangle',
        material: 'metal',
        points: 100,
      },
      {
        x: 585,
        y: 420,
        width: 40,
        height: 40,
        type: 'rectangle',
        material: 'wood',
        points: 75,
      },
    ],
    obstacles: [],
    requiredScore: 175,
    stars: { one: 175, two: 210, three: 225 },
  },
  {
    id: 7,
    name: 'Domino Etkisi',
    description: 'Zincirleme reaksiyon başlat!',
    projectiles: [{ type: 'normal', count: 2 }],
    targets: [
      {
        x: 700,
        y: 480,
        width: 30,
        height: 40,
        type: 'rectangle',
        material: 'wood',
        points: 100,
      },
    ],
    obstacles: [
      {
        x: 500,
        y: 470,
        width: 15,
        height: 50,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 540,
        y: 470,
        width: 15,
        height: 50,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 580,
        y: 470,
        width: 15,
        height: 50,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 620,
        y: 470,
        width: 15,
        height: 50,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 660,
        y: 470,
        width: 15,
        height: 50,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
    ],
    requiredScore: 100,
    stars: { one: 100, two: 150, three: 200 },
  },
  {
    id: 8,
    name: 'Yüksek Kule',
    description: 'Yüksek yapıyı yıkmak için doğru açıyı bul!',
    projectiles: [{ type: 'normal', count: 4 }],
    targets: [
      {
        x: 600,
        y: 280,
        radius: 25,
        type: 'circle',
        material: 'wood',
        points: 150,
      },
    ],
    obstacles: [
      {
        x: 570,
        y: 480,
        width: 20,
        height: 80,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 630,
        y: 480,
        width: 20,
        height: 80,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 600,
        y: 410,
        width: 80,
        height: 15,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 570,
        y: 360,
        width: 20,
        height: 60,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 630,
        y: 360,
        width: 20,
        height: 60,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
      {
        x: 600,
        y: 320,
        width: 80,
        height: 15,
        type: 'rectangle',
        material: 'wood',
        isStatic: false,
      },
    ],
    requiredScore: 150,
    stars: { one: 150, two: 200, three: 250 },
  },
  {
    id: 9,
    name: 'Piramit',
    description: 'Karmaşık piramit yapısını çökert!',
    projectiles: [{ type: 'heavy', count: 1 }, { type: 'normal', count: 3 }],
    targets: [
      // Base layer
      {
        x: 550,
        y: 490,
        width: 35,
        height: 35,
        type: 'rectangle',
        material: 'wood',
        points: 30,
      },
      {
        x: 600,
        y: 490,
        width: 35,
        height: 35,
        type: 'rectangle',
        material: 'wood',
        points: 30,
      },
      {
        x: 650,
        y: 490,
        width: 35,
        height: 35,
        type: 'rectangle',
        material: 'wood',
        points: 30,
      },
      // Second layer
      {
        x: 575,
        y: 445,
        width: 35,
        height: 35,
        type: 'rectangle',
        material: 'glass',
        points: 50,
      },
      {
        x: 625,
        y: 445,
        width: 35,
        height: 35,
        type: 'rectangle',
        material: 'glass',
        points: 50,
      },
      // Top
      {
        x: 600,
        y: 400,
        radius: 20,
        type: 'circle',
        material: 'metal',
        points: 100,
      },
    ],
    obstacles: [],
    requiredScore: 200,
    stars: { one: 200, two: 250, three: 290 },
  },
  {
    id: 10,
    name: 'Usta Seviyesi',
    description: 'Tüm becerilerini kullan! En zor seviye!',
    projectiles: [
      { type: 'bouncy', count: 2 },
      { type: 'heavy', count: 1 },
      { type: 'normal', count: 2 },
    ],
    targets: [
      {
        x: 500,
        y: 300,
        radius: 15,
        type: 'circle',
        material: 'glass',
        points: 75,
      },
      {
        x: 700,
        y: 400,
        radius: 15,
        type: 'circle',
        material: 'glass',
        points: 75,
      },
      {
        x: 600,
        y: 250,
        width: 30,
        height: 30,
        type: 'rectangle',
        material: 'wood',
        points: 100,
      },
    ],
    obstacles: [
      // Bottom platforms
      {
        x: 450,
        y: 480,
        width: 100,
        height: 10,
        type: 'rectangle',
        material: 'stone',
        isStatic: true,
        angle: 0.2,
      },
      {
        x: 650,
        y: 480,
        width: 100,
        height: 10,
        type: 'rectangle',
        material: 'stone',
        isStatic: true,
        angle: -0.2,
      },
      // Middle barriers
      {
        x: 550,
        y: 380,
        width: 15,
        height: 80,
        type: 'rectangle',
        material: 'metal',
        isStatic: false,
      },
      {
        x: 650,
        y: 380,
        width: 15,
        height: 80,
        type: 'rectangle',
        material: 'metal',
        isStatic: false,
      },
      // Top platform
      {
        x: 600,
        y: 300,
        width: 120,
        height: 10,
        type: 'rectangle',
        material: 'stone',
        isStatic: true,
      },
    ],
    requiredScore: 200,
    stars: { one: 200, two: 240, three: 250 },
  },
];

